### ISSUE TITLE
Dispenser gun not using ammo; reload skill has no sound

### ISSUE THREAD

**Issue by LcorpOfficial** [LcorpOfficial/LCC-Minecraft-Server#48]
**Describe the bug**
[04:38:14 WARN]: [MythicMobs] Couldn't execute skill 'dispensergunreload': Enable debugging for a stack trace.

```
dispensergunreload:
  Cooldown: 0.8
  Conditions:
  - equipslot HAND
  Skills:
  - reloadammo{}
  - effect:sound{s=item.bottle.fill_dragonbreath;v=0.3;p=0.8} @self
  - effect:sound{s=block.piston.contract;v=0.2;p=1.5}
  - effect:sound{s=block.iron_door.open;v=0.5;p=0.7}
```

**Expected behavior**
  - effect:sound{s=block.piston.contract;v=0.2;p=1.5}
  - effect:sound{s=block.iron_door.open;v=0.5;p=0.7}
**Screenshots**

**Minecraft Info (please complete the following information):**
 - Client: Alphaship
 - Version: MM 4.11.0 MythicCrucible current
 - Mods (if any):

**Additional context notes**
