### ISSUE TITLE
guard loot re-ballance

### ISSUE THREAD

**Issue by xanderstuff** [LcorpOfficial/LCC-Minecraft-Server#53]
I think guard captains should drop about 3x more money than normal guards

**Comment by LcorpOfficial** [comment]
updated GuardCaptain's loot table as follows:
```
midtier:
  Conditions:
  - playerwithin 40
  Drops:
  - exp 75-125 1
  - money 250-650
  - mcmmo-exp 4-10
```
now using tier-structure for generic drops (moiey/xp)
